# Generated by Django 2.2.7 on 2019-11-13 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabungan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='exp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='level',
        ),
    ]
